#!/usr/bin/env python3
"""
spec_to_manifest.py — Playwright .spec.ts → parse_tsu-shaped manifest JSON.

Used by gen_tsu.py via `--spec`. Walks the spec tree-sitter AST, cross-
references locator texts against a `pages/*.page.ts` catalog, reconstructs
folder/block/control-flow structure from comments, and emits a manifest
that matches the schema parse_tsu produces.

Three input shapes the parser tries to handle:

1. **Inline with comments** (auto-generated by parse_tsu, the round-trip path):
   - `// CDE | Cookie window`            → module name marker
   - `// Click Submit btn`               → step name
   - `// ── Folder Name`                 → folder boundary
   - `// [if Foo] condition: 1=="1"`     → control flow open
   - `// [Then]` / `// [Else]` / `// [Loop]` → branch open
   - `// [end if Foo]`                   → control flow close
   - `// TBox Wait: 3000 ms`             → synthesizes wait step
   - `await page.locator(…).click()`     → action

2. **POM-style** (`pageObj.field.action()`): the field reference is resolved
   through the page-objects catalog (locator text + module + attribute name).

3. **Bare inline** (no comments, no POM imports): each locator is matched
   against the page-objects catalog by source text; if not found, the step
   is emitted with a synthetic module name so the user can hand-fix.

Public entry point:
    build_manifest_from_spec(spec_path, pages_dir, base_manifest=None)
        → dict in parse_tsu manifest format
"""

import re
from pathlib import Path
from collections import defaultdict
import tree_sitter as ts
import tree_sitter_typescript as tsts


# ──────────────────────────────────────────────────────────────────────────────
# Tree-sitter setup
# ──────────────────────────────────────────────────────────────────────────────
_LANG = ts.Language(tsts.language_typescript())
_PARSER = ts.Parser(_LANG)


def _src(node, source: bytes) -> str:
    """Return the literal source text of a node."""
    return source[node.start_byte:node.end_byte].decode('utf-8', errors='replace')


def _children_by_type(node, type_name: str):
    return [c for c in node.children if c.type == type_name]


# ──────────────────────────────────────────────────────────────────────────────
# Page-object parser  →  catalog
# ──────────────────────────────────────────────────────────────────────────────
# Each catalog entry: {
#     'class_name':  'LoginPagePage',
#     'module_name': 'Login page',          # derived; user can override via JSON map
#     'fields':      [{'name': 'email_address', 'locator_text': 'page.locator(\'#signInName\')'}],
# }
#
# We also build a reverse index normalized_locator_text → (class_name, field_name)
# so that the spec parser can match `page.locator('#signInName')` back to
# (LoginPagePage, email_address).

_FIELD_ASSIGN_QUERY = _LANG.query("""
(assignment_expression
  left: (member_expression
    object: (this)
    property: (property_identifier) @field)
  right: (_) @rhs) @assign
""")


def _camel_to_words(name: str) -> str:
    """LoginPagePage → 'Login Page'  (drop trailing 'Page' if present)."""
    if name.endswith('Page'):
        name = name[:-4]
    parts = re.findall(r'[A-Z][a-z0-9]*|[a-z0-9]+', name)
    return ' '.join(p.capitalize() for p in parts) if parts else name


def _normalize_locator_text(text: str) -> str:
    """Collapse whitespace + line continuations so two formattings match."""
    t = re.sub(r'\s+', ' ', text)
    t = re.sub(r'\s*\.\s*', '.', t)
    t = re.sub(r'\s*,\s*', ', ', t)
    return t.strip()


def parse_pages_dir(pages_dir: Path):
    """Walk a pages/ directory; return list of {class_name, module_name, fields[]}.

    Plus a reverse map: { normalized_locator_text → (class_name, field_name) }."""
    catalog = []
    rev_index = {}

    for ts_path in sorted(pages_dir.glob('*.page.ts')):
        source = ts_path.read_bytes()
        tree = _PARSER.parse(source)
        root = tree.root_node
        # find each class declaration
        for cls_node in _walk_find(root, 'class_declaration'):
            name_node = cls_node.child_by_field_name('name')
            if not name_node: continue
            class_name = _src(name_node, source)
            # Constructor body: find method with name='constructor'
            ctor = _find_constructor(cls_node)
            fields = []
            if ctor is not None:
                body = ctor.child_by_field_name('body')
                if body:
                    matches = _FIELD_ASSIGN_QUERY.matches(body)
                    for _id, captures in matches:
                        field_node = captures.get('field', [None])[0]
                        rhs_node = captures.get('rhs', [None])[0]
                        if field_node is None or rhs_node is None: continue
                        fname = _src(field_node, source)
                        if fname == 'page':  # skip the 'this.page = page;' binding
                            continue
                        rhs_text = _src(rhs_node, source)
                        fields.append({'name': fname, 'locator_text': rhs_text})
                        rev_index[_normalize_locator_text(rhs_text)] = (class_name, fname)
                        # Also index the .or(...) right-hand-side primary alone, so that
                        # specs that drop the .or() fallback can still match.
                        primary_only = re.split(r'\s*\.\s*or\s*\(', rhs_text)[0]
                        rev_index.setdefault(_normalize_locator_text(primary_only),
                                              (class_name, fname))
            catalog.append({
                'class_name':  class_name,
                'module_name': _camel_to_words(class_name),
                'pages_file':  str(ts_path),
                'fields':      fields,
            })
    return catalog, rev_index


def _walk_find(node, type_name: str):
    """DFS yield all descendants of a given type."""
    if node.type == type_name:
        yield node
    for c in node.children:
        yield from _walk_find(c, type_name)


def _find_constructor(class_node):
    body = class_node.child_by_field_name('body')
    if not body: return None
    for c in body.children:
        if c.type == 'method_definition':
            name = c.child_by_field_name('name')
            if name and name.type == 'property_identifier':
                if name.text == b'constructor':
                    return c
    return None


# ──────────────────────────────────────────────────────────────────────────────
# Spec parser  →  flat node stream (manifest.steps shape)
# ──────────────────────────────────────────────────────────────────────────────
# We walk the spec linearly: every comment gets read in order, every
# `await page.<...>.<action>(...)` becomes a tentative action. A comment-state
# machine emits folder/block/if/then/else/loop/step boundary nodes.

# Structured @tosca markers (emitted by parse_tsu.py for unambiguous round-trip).
# These are the PRIMARY source of structural truth; legacy heuristics below are
# fallback for hand-written specs without markers.
TOSCA_MARKERS = [
    ('folder_open',  re.compile(r'^//\s*@tosca\s+folder:\s*"((?:\\.|[^"])*)"\s*$')),
    ('folder_close', re.compile(r'^//\s*@tosca\s+/folder\s*$')),
    ('block_open',   re.compile(r'^//\s*@tosca\s+block:\s*"((?:\\.|[^"])*)"\s*$')),
    ('block_close',  re.compile(r'^//\s*@tosca\s+/block\s*$')),
    ('if_open',      re.compile(r'^//\s*@tosca\s+if:\s*"((?:\\.|[^"])*)"\s+cond="((?:\\.|[^"])*)"(?:\s+verdict=(True|False))?\s*$')),
    ('if_close',     re.compile(r'^//\s*@tosca\s+/if\s*$')),
    ('branch_open',  re.compile(r'^//\s*@tosca\s+(then|else|loop)\s*$')),
    ('branch_close', re.compile(r'^//\s*@tosca\s+/branch\s*$')),
    ('step_marker',  re.compile(r'^//\s*@tosca\s+step:\s*"((?:\\.|[^"])*)"\s+module="((?:\\.|[^"])*)"\s*$')),
    ('wait_marker',  re.compile(r'^//\s*@tosca\s+wait:\s*(\d+)(?:\s+name="((?:\\.|[^"])*)")?\s*$')),
    ('buffers',      re.compile(r'^//\s*@tosca\s+buffers:\s*(.*)$')),
]

# Legacy heuristic patterns (used only when no @tosca markers are present in
# the spec — i.e. for hand-written specs). They're noisier but degrade
# gracefully.
LEGACY_PATTERNS = [
    ('folder',         re.compile(r'^//\s*──\s*(.+?)\s*$')),
    ('legacy_if_open', re.compile(r'^//\s*\[if\s+(.+?)\]\s*condition:\s*(.*?)(?:\s*→\s*(True|False))?\s*$')),
    ('legacy_branch',  re.compile(r'^//\s*\[(Then|Else|Loop)\]\s*$')),
    ('legacy_if_close',re.compile(r'^//\s*\[end if\s+(.+?)\]\s*$')),
    ('legacy_wait',    re.compile(r'^//\s*TBox Wait:\s*(\d+)\s*ms\s*$')),
    ('encrypted',      re.compile(r'^//\s*.+Tosca-encrypted')),
    ('step_or_module', re.compile(r'^//\s*(.+?)\s*$')),
]


def _unquote(s: str) -> str:
    """Reverse the _mq() escape used by parse_tsu's marker emitter."""
    return s.replace('\\"', '"').replace('\\\\', '\\')


PLAYWRIGHT_ACTIONS = {
    # action method → manifest mode
    'click':       ('set',         '{Click}'),
    'dblclick':    ('set',         '{DOUBLECLICK}'),
    'fill':        ('set',         None),  # value comes from arg
    'press':       ('set',         None),  # value formatted as {KEY[arg]}
    'pressSequentially': ('set',   None),
    'hover':       ('set',         '{HOVER}'),
    'check':       ('set',         '{Click}'),
    'uncheck':     ('set',         '{Click}'),
    'selectOption': ('set',        None),
    'focus':       ('set',         '{FOCUS}'),
    'blur':        ('set',         '{BLUR}'),
    'scrollIntoViewIfNeeded': ('set', '{SCROLLINTOVIEW}'),
    'textContent': ('bufferRead',  ''),
    'innerText':   ('bufferRead',  ''),
    'inputValue':  ('bufferRead',  ''),
}

# expect(...).<matcher>(...) — manifest mode='verify' or 'waitFor'
EXPECT_MATCHERS = {
    'toBeVisible':   ('verify',  'Visible',  'True'),
    'toBeHidden':    ('verify',  'Visible',  'False'),
    'toBeEnabled':   ('verify',  'Enabled',  'True'),
    'toBeDisabled':  ('verify',  'Disabled', 'True'),
    'toBeChecked':   ('verify',  'Checked',  'True'),
    'toBeFocused':   ('verify',  'Focused',  'True'),
    'toBeEditable':  ('verify',  'Editable', 'True'),
    'toBeAttached':  ('verify',  'Exists',   'True'),
    'toContainText': ('verify',  '',         None),  # value is the text arg
    'toHaveText':    ('verify',  '',         None),
    'toHaveValue':   ('verify',  'Value',    None),
    'toHaveCount':   ('verify',  'Count',    None),
}


def _strip_or_chain(loc_text: str) -> str:
    """For inline `(page.locator(X)).or(page.locator(Y))` — return primary only."""
    return re.split(r'\s*\.\s*or\s*\(', loc_text)[0].strip().lstrip('(').rstrip(')').strip()


# Chain methods that decorate a locator/action without being the action itself.
# When identifying the action verb (rightmost meaningful call), skip these.
CHAIN_DECORATORS_TAIL = {'catch'}     # comes AFTER the action: .click({...}).catch(...)
CHAIN_DECORATORS_MID  = {'first', 'filter', 'nth'}  # locator decorators: .first()/.filter()/.nth()


def _strip_action_options(args_text: str) -> str:
    """Strip Playwright action option objects from args. The option object
    can be the only argument (.click({timeout:3000})) or trail a value
    (.fill('hi', {timeout:3000})). We detect a trailing ',' followed by
    '{' OR a leading '{' if no preceding string/identifier."""
    s = args_text.strip()
    if not s: return s
    # Trailing option object: 'value', { ... }
    s = re.sub(r',\s*\{[^}]*\}\s*$', '', s)
    # Sole option object: { timeout: 3000 } as the only arg
    if re.match(r'^\{[^}]*\}\s*$', s):
        return ''
    return s


def _strip_locator_decorators(loc_text: str) -> str:
    """Strip trailing locator decorators (.first(), .filter({...}), .nth(N))
    so the locator text matches what's in the page-objects catalog."""
    s = loc_text.strip()
    # Iteratively strip suffix decorators
    while True:
        m = re.search(r'\.(first|filter|nth)\([^)]*\)\s*$', s)
        if not m: break
        s = s[:m.start()].rstrip()
    return s


def _key_arg_to_token(arg: str) -> str:
    """'Control+a' → '{KEY[Control+a]}', 'Tab' → '{TAB}', 'Delete' → '{DELETE}'."""
    a = arg.strip().strip('"\'')
    bare_keys = {'Tab','Enter','Escape','Space','Home','End','Backspace','Delete',
                 'ArrowUp','ArrowDown','ArrowLeft','ArrowRight'}
    if a in bare_keys:
        return '{' + a.upper() + '}'
    return '{KEY[' + a + ']}'


def _parse_action_arg(arg_text: str) -> str:
    """Extract a literal string arg from a function call argument expression."""
    arg_text = arg_text.strip()
    # Strip trailing nullish coalescing: `process.env.X ?? ''` → 'process.env.X'
    arg_text = re.sub(r'\s*\?\?\s*[\'"][^\'\"]*[\'"]$', '', arg_text)
    # `process.env.FOO` → '{CP[FOO]}' so re-emission round-trips
    m = re.match(r'^process\.env\.([A-Z0-9_]+)\s*$', arg_text)
    if m: return '{CP[' + m.group(1) + ']}'
    # String literal
    m = re.match(r'^[\'"](.*)[\'"]$', arg_text, re.DOTALL)
    if m: return m.group(1)
    return arg_text


def _walk_stream(root, source: bytes):
    """Yield (line_no, kind, payload) tuples in document order.

    kind ∈ {'comment', 'await_call', 'test_step_open', 'test_step_close', 'test_open', 'test_close'}.
    payload differs by kind.
    """
    # Strategy: walk all descendants; collect interesting nodes; sort by start_byte.
    items = []
    for n in _walk_find(root, 'comment'):
        items.append((n.start_byte, 'comment', n))
    # await expressions
    for n in _walk_find(root, 'await_expression'):
        items.append((n.start_byte, 'await', n))
    # `test(...)` and `test.step(...)` calls
    for n in _walk_find(root, 'call_expression'):
        fn = n.child_by_field_name('function')
        if fn is None: continue
        text = _src(fn, source)
        if text == 'test' or text.startswith('test('):
            items.append((n.start_byte, 'test_open', n))
        elif text == 'test.step':
            items.append((n.start_byte, 'test_step_open', n))
        # `test.use(...)` is the per-spec config override emitted by parse_tsu;
        # it's metadata, not a test step. Skip it explicitly so the call doesn't
        # get treated as anything else later in the walk.
        # (No item added for test.use; it's just ignored.)
    items.sort(key=lambda it: it[0])
    return items


def _arg_node_text(call_node, source: bytes) -> str:
    args = call_node.child_by_field_name('arguments')
    if args is None: return ''
    return _src(args, source)


def _call_chain(node, source: bytes):
    """Walk a call chain like `page.locator('#x').or(page.locator('#y')).fill('hi')`
    and return list of (method, args_text) in left-to-right order."""
    chain = []

    def visit(n):
        if n.type == 'call_expression':
            fn = n.child_by_field_name('function')
            args = n.child_by_field_name('arguments')
            if fn is not None and fn.type == 'member_expression':
                obj = fn.child_by_field_name('object')
                method = fn.child_by_field_name('property')
                if obj is not None: visit(obj)
                if method is not None:
                    args_text = _src(args, source) if args else ''
                    # arg text is "(...)" — strip outer parens
                    if args_text.startswith('(') and args_text.endswith(')'):
                        args_text = args_text[1:-1]
                    chain.append((_src(method, source), args_text))
            else:
                # bare function call like `expect(loc)`
                if fn is not None:
                    chain.append((_src(fn, source), _arg_node_text(n, source).strip('()')))
        elif n.type == 'member_expression':
            obj = n.child_by_field_name('object')
            prop = n.child_by_field_name('property')
            if obj: visit(obj)
            if prop: chain.append((_src(prop, source), None))   # property access, no args
        elif n.type == 'parenthesized_expression':
            inner = n.children[1] if len(n.children) > 2 else None
            if inner: visit(inner)
        # else: leaf (identifier, etc.) — terminator

    visit(node)
    return chain


# ──────────────────────────────────────────────────────────────────────────────
# Manifest builder
# ──────────────────────────────────────────────────────────────────────────────
class SpecToManifest:
    def __init__(self, page_catalog, rev_index, base_manifest=None):
        self.catalog = page_catalog
        self.rev_index = rev_index
        self.base = base_manifest or {}
        # Comment-state
        self.last_step_name = ''
        self.last_module_name = ''
        self.next_step_module = ''       # set by the next @tosca step: marker
        self.next_step_name = ''
        self.pending_step_actions = []   # accumulator until next step boundary
        # Output manifest
        self.steps = []
        self.test_data = dict(self.base.get('test_data', {}))
        self.unmapped = []
        self.test_name = ''
        # Folder/block stack
        self.folder_stack = []           # depth tracking
        # Control-flow open conditions (so we can emit if_end with the right name)
        self.if_stack = []               # list of names

    # ── public ─────────────────────────────────────────────────────────────
    def build(self, spec_path: Path) -> dict:
        source = spec_path.read_bytes()
        tree = _PARSER.parse(source)
        root = tree.root_node
        # Top-level test() name — first call to test(...)
        for n in _walk_find(root, 'call_expression'):
            fn = n.child_by_field_name('function')
            if fn is not None and _src(fn, source) == 'test':
                args = n.child_by_field_name('arguments')
                if args and len(args.children) >= 2:
                    first_arg = args.children[1]  # skip '('
                    if first_arg.type in ('string', 'template_string'):
                        self.test_name = _parse_action_arg(_src(first_arg, source))
                        break
        # Drive the comment+await stream
        self._drive_stream(root, source)
        # Flush any pending step actions
        self._flush_step()
        return {
            'meta': {
                'test_name':   self.test_name,
                'project':     self.base.get('meta', {}).get('project', ''),
                'base_url':    self.base.get('meta', {}).get('base_url', ''),
                'all_urls':    self.base.get('meta', {}).get('all_urls', []),
                'config':      self.base.get('meta', {}).get('config', {}),
                'unmapped':    self.unmapped,
            },
            'test_data': self.test_data,
            'steps':     self.steps,
        }

    # ── stream drive ───────────────────────────────────────────────────────
    def _drive_stream(self, root, source):
        items = _walk_stream(root, source)
        # Detect whether the spec is structured (has @tosca markers) or legacy.
        self.has_markers = any(
            kind == 'comment' and '@tosca' in _src(node, source)
            for _, kind, node in items
        )
        # test_step_open emits a folder boundary; @tosca folder/block markers
        # supersede that for nested levels.
        for byte, kind, node in items:
            if kind == 'comment':
                self._on_comment(_src(node, source).strip(), source)
            elif kind == 'test_step_open':
                # Top-level await test.step("...") — only treat as folder open
                # when we DON'T already have an active @tosca folder/block from
                # the marker comment that immediately precedes it.
                args = node.child_by_field_name('arguments')
                name = ''
                if args and len(args.children) >= 2:
                    n0 = args.children[1]
                    if n0.type in ('string','template_string'):
                        name = _parse_action_arg(_src(n0, source))
                if not self.has_markers:
                    self._flush_step()
                    self._close_folders_to_depth(0)
                    self._open_folder(name)
                # When markers present, the @tosca folder/block markers already
                # opened the right kind; we just consume the test.step call as
                # a no-op container and let nested awaits/comments populate.
            elif kind == 'await':
                self._on_await(node, source)

    # ── comment handling ───────────────────────────────────────────────────
    def _on_comment(self, text: str, source):
        # 1) Structured markers (preferred)
        for kind, pat in TOSCA_MARKERS:
            m = pat.match(text)
            if not m: continue
            return self._on_marker(kind, m)
        # 2) Legacy heuristics (only when no markers in spec)
        if self.has_markers:
            return  # ignore decorative comments when markers are authoritative
        for kind, pat in LEGACY_PATTERNS:
            m = pat.match(text)
            if not m: continue
            return self._on_legacy(kind, m)

    def _on_marker(self, kind: str, m):
        if kind == 'folder_open':
            self._flush_step()
            self._open_folder(_unquote(m.group(1)))
        elif kind == 'folder_close':
            self._flush_step()
            self._close_folder()
        elif kind == 'block_open':
            self._flush_step()
            self._open_block(_unquote(m.group(1)))
        elif kind == 'block_close':
            self._flush_step()
            self._close_block()
        elif kind == 'if_open':
            self._flush_step()
            name = _unquote(m.group(1))
            cond = _unquote(m.group(2))
            verdict = m.group(3)
            node = {'type': 'if', 'name': name, 'condition': cond,
                    'depth': len(self.folder_stack)}
            if verdict:
                node['condition_resolved'] = ('1=="1"' if verdict == 'True' else '0=="1"')
            self.steps.append(node)
            self.if_stack.append(name)
        elif kind == 'if_close':
            self._flush_step()
            name = self.if_stack.pop() if self.if_stack else ''
            self.steps.append({'type': 'if_end', 'name': name,
                                'depth': len(self.folder_stack)})
        elif kind == 'branch_open':
            self._flush_step()
            kw = m.group(1).lower() + '_start'
            self.steps.append({'type': kw, 'name': m.group(1).title(),
                                'depth': len(self.folder_stack)})
        elif kind == 'branch_close':
            self._flush_step()
            # Determine which branch is closing: the most recent open one.
            # We don't track explicitly; assume then→then_end, else→else_end, loop→loop_end
            # based on the trailing branch_start. For simplicity emit `then_end` style based
            # on inspection of the last branch_start node in self.steps.
            kind_name = self._last_branch_kind()
            self.steps.append({'type': kind_name + '_end', 'name': kind_name.title(),
                                'depth': len(self.folder_stack)})
        elif kind == 'step_marker':
            # Each @tosca step: marker delimits one logical step. We push a
            # step entry immediately; awaited action calls between this marker
            # and the next structural marker append to its actions list.
            # Steps with no actions (skipped TBox modules) round-trip cleanly
            # this way.
            self._flush_step()
            self.last_step_name   = _unquote(m.group(1))
            self.last_module_name = _unquote(m.group(2))
            self.pending_step_actions = (self.last_step_name, self.last_module_name), []
        elif kind == 'wait_marker':
            self._flush_step()
            ms = m.group(1)
            wait_name = _unquote(m.group(2) or '') or 'TBox Wait'
            self.steps.append({
                'type': 'step', 'name': wait_name, 'module': 'TBox Wait',
                'depth': len(self.folder_stack),
                'actions': [{'mode': 'set', 'element': 'Duration', 'value': ms}],
            })
        elif kind == 'buffers':
            # `// @tosca buffers: A=value1; B=value2; ...` — append to the
            # pending step set up by the prior @tosca step marker. The step
            # marker named the step (e.g. "Set buffer for tinted product");
            # buffers carries the actual XTestStepValues.
            kvs = m.group(1).strip()
            buf_actions = []
            for chunk in [c.strip() for c in kvs.split(';') if c.strip()]:
                if '=' not in chunk: continue
                k, v = chunk.split('=', 1)
                k = k.strip(); v = v.strip()
                buf_actions.append({'mode': 'set', 'element': '<Buffername>',
                                     'value': v, 'explicit_name': k})
                self.test_data[k] = v
            if buf_actions:
                if (self.pending_step_actions
                        and self.pending_step_actions[0][1] == 'TBox Set Buffer'):
                    # Append to the existing pending step
                    self.pending_step_actions[1].extend(buf_actions)
                else:
                    # No prior step marker — create a fresh one
                    self._flush_step()
                    self.pending_step_actions = (
                        ('Set Buffers', 'TBox Set Buffer'), buf_actions
                    )

    def _last_branch_kind(self) -> str:
        """Look back through steps to find the most recently opened
        then/else/loop_start that hasn't been closed yet."""
        depth = 0
        for s in reversed(self.steps):
            t = s.get('type', '')
            if t.endswith('_end') and t.split('_')[0] in ('then', 'else', 'loop'):
                depth += 1
            elif t.endswith('_start') and t.split('_')[0] in ('then', 'else', 'loop'):
                if depth == 0:
                    return t.split('_')[0]
                depth -= 1
        return 'then'

    def _on_legacy(self, kind: str, m):
        if kind == 'folder':
            self.last_module_name = m.group(1)
        elif kind == 'legacy_if_open':
            self._flush_step()
            cond = m.group(2); verdict = m.group(3)
            node = {'type': 'if', 'name': m.group(1), 'condition': cond,
                    'depth': len(self.folder_stack)}
            if verdict:
                node['condition_resolved'] = ('1=="1"' if verdict == 'True' else '0=="1"')
            self.steps.append(node)
            self.if_stack.append(m.group(1))
        elif kind == 'legacy_branch':
            self._flush_step()
            kw = m.group(1).lower() + '_start'
            self.steps.append({'type': kw, 'name': m.group(1), 'depth': len(self.folder_stack)})
        elif kind == 'legacy_if_close':
            self._flush_step()
            name = self.if_stack.pop() if self.if_stack else m.group(1)
            self.steps.append({'type': 'if_end', 'name': name, 'depth': len(self.folder_stack)})
        elif kind == 'legacy_wait':
            self._flush_step()
            ms = m.group(1)
            self.steps.append({
                'type': 'step', 'name': 'TBox Wait', 'module': 'TBox Wait',
                'depth': len(self.folder_stack),
                'actions': [{'mode': 'set', 'element': 'Duration', 'value': ms}],
            })
        elif kind == 'encrypted':
            pass
        elif kind == 'step_or_module':
            txt = m.group(1)
            if '|' in txt:
                self.last_module_name = txt.split('|', 1)[0].strip()
            self.last_step_name = txt

    # ── await call handling ────────────────────────────────────────────────
    def _on_await(self, await_node, source):
        # await_expression → call_expression chain
        # We want the leftmost terminator (locator builder) and the final method
        # (the action verb).
        # Find the inner call_expression (the awaited thing)
        inner = None
        for c in await_node.children:
            if c.type == 'call_expression':
                inner = c
                break
        if inner is None: return
        chain = _call_chain(inner, source)
        if not chain: return
        # chain is a list of (method, args). The locator-construction part is the
        # prefix; the last call is the action.
        # Identify expect(...) chains specially.
        head_method, head_args = chain[0] if chain else (None, None)
        if head_method == 'expect':
            self._handle_expect(chain, source)
            return
        # For await page.locator(...).fill(...): chain is
        #   [('page', None), ('locator','"#x"'), ('fill','"hi"')]
        # parse_tsu now also emits decorators around the action:
        #   [..., ('first', ''), ('click', '{ timeout: 3000 }'), ('catch', '() => {}')]
        # Strip trailing tail decorators (.catch) before identifying the action.
        i = len(chain) - 1
        while i >= 0 and chain[i][0] in CHAIN_DECORATORS_TAIL:
            i -= 1
        if i < 0: return
        action_method, action_args = chain[i]
        # Strip mid-chain locator decorators (.first, .filter, .nth) when
        # building the builder_chain so the locator text matches catalog form.
        builder_chain = [c for c in chain[:i] if c[0] not in CHAIN_DECORATORS_MID]
        # Action verb in PLAYWRIGHT_ACTIONS?
        if action_method not in PLAYWRIGHT_ACTIONS:
            # Unknown — emit as TODO note and move on (likely page.goto, page.waitForTimeout)
            if action_method == 'waitForTimeout':
                # Already handled by TBox Wait comment; ignore here.
                return
            return
        mode, fixed_value = PLAYWRIGHT_ACTIONS[action_method]
        # Compute value
        if fixed_value is not None:
            value = fixed_value
        else:
            # action_args may include trailing options like ', { timeout: 3000 }'
            # or be just the options object alone (when the action has no value
            # arg, e.g. .click({timeout: 3000})). Strip options before parsing.
            action_args = _strip_action_options(action_args or '')
            # Convert action args to a Tosca value
            if action_method == 'press':
                value = _key_arg_to_token(action_args or '')
            elif action_method == 'selectOption':
                # selectOption("X") → {SELECT[X]}; selectOption({index:N}) → {SELECT[N+1]}
                m = re.match(r'\{\s*index\s*:\s*(\d+)\s*\}', (action_args or '').strip())
                if m:
                    value = '{SELECT[' + str(int(m.group(1))+1) + ']}'
                else:
                    value = '{SELECT[' + _parse_action_arg(action_args or '') + ']}'
            else:
                value = _parse_action_arg(action_args or '')
        # Build locator text from builder_chain
        loc_text = self._chain_to_locator_text(builder_chain, source)
        # Reverse-lookup against catalog
        module, attr = self._resolve_locator(loc_text)
        # Step name from latest non-special comment, module from prior context
        step_name = self.last_step_name or 'step'
        module_name = module or self.last_module_name or ''
        self._emit_or_extend_step(step_name, module_name, {
            'mode': mode,
            'element': attr or '',
            'value': value,
            'locator': {'primary': loc_text} if loc_text else None,
        })

    def _handle_expect(self, chain, source):
        # chain looks like [('expect', '<arg>'), ('matcher', '<arg>'), ...]
        if len(chain) < 2: return
        _, expect_arg = chain[0]
        # subject of expect — that's the locator. Strip outer parens; this is
        # the source text we look up.
        subject = (expect_arg or '').strip()
        # Some chains have intermediate `.not` (chain[1] = ('not', None))
        matcher_idx = 1
        is_not = False
        if matcher_idx < len(chain) and chain[matcher_idx][0] == 'not':
            is_not = True
            matcher_idx += 1
        if matcher_idx >= len(chain): return
        matcher, m_args = chain[matcher_idx]
        if matcher not in EXPECT_MATCHERS:
            return
        mode, prop, fixed_val = EXPECT_MATCHERS[matcher]
        # Apply 'not' inversion for boolean matchers
        if is_not and prop in ('Visible', 'Enabled', 'Checked', 'Focused', 'Editable',
                                'Disabled', 'Exists', 'ReadOnly'):
            # Invert: orig matcher result → flip the True/False
            # For simplicity, we keep prop and toggle by setting value to 'False'
            value_default = 'False'
        else:
            value_default = 'True'
        if fixed_val is None:
            # Value is the matcher arg
            value = _parse_action_arg(m_args or '')
            if matcher == 'toContainText': value = '*' + value + '*'
        else:
            value = value_default
        loc_text = self._normalize_subject(subject)
        # Strip trailing locator decorators (.first()/.filter()) before catalog
        # lookup; preserve original loc_text in the manifest so re-emission
        # round-trips faithfully.
        lookup_text = _strip_locator_decorators(loc_text)
        module, attr = self._resolve_locator(lookup_text)
        step_name = self.last_step_name or 'verify'
        module_name = module or self.last_module_name or ''
        self._emit_or_extend_step(step_name, module_name, {
            'mode': mode,
            'element': attr or '',
            'value': value,
            'property': prop,
            'locator': {'primary': loc_text} if loc_text else None,
        })

    def _normalize_subject(self, subject: str) -> str:
        s = subject.strip()
        if s.startswith('(') and s.endswith(')'):
            s = s[1:-1].strip()
        return s

    def _chain_to_locator_text(self, builder_chain, source) -> str:
        """Given a chain like [('page',None),('locator','"#x"'),('or','page.locator(\"y\")')],
        reconstruct the original source text — easier: take the leftmost call's
        node and rebuild the full text up to (but not including) the action verb."""
        # Build by joining: <head>.<m1>(args1).<m2>(args2)...
        if not builder_chain: return ''
        out = []
        for i, (m, a) in enumerate(builder_chain):
            if i == 0:
                out.append(m)
            else:
                if a is None:
                    out.append('.' + m)        # property access (e.g. .nth)
                else:
                    out.append('.' + m + '(' + a + ')')
        return ''.join(out)

    def _resolve_locator(self, loc_text: str):
        """Match loc_text against page-objects catalog. Returns (module, attribute)
        or (None, None) if unmatched."""
        if not loc_text: return None, None
        norm = _normalize_locator_text(loc_text)
        if norm in self.rev_index:
            class_name, field_name = self.rev_index[norm]
            module = self._class_to_module(class_name)
            return module, self._field_to_attr(class_name, field_name)
        # Try primary-only (strip .or fallback)
        primary = _strip_or_chain(loc_text)
        norm_p = _normalize_locator_text(primary)
        if norm_p in self.rev_index:
            class_name, field_name = self.rev_index[norm_p]
            return self._class_to_module(class_name), self._field_to_attr(class_name, field_name)
        return None, None

    def _class_to_module(self, class_name: str) -> str:
        for c in self.catalog:
            if c['class_name'] == class_name:
                return c['module_name']
        return _camel_to_words(class_name)

    def _field_to_attr(self, class_name, field_name):
        # Snake-case → original attr name (best-effort): "email_address" → "email address"
        # The catalog doesn't carry the original Tosca attribute name; the
        # manifest builder layer can substitute the env's true name when the
        # base .tsu has it.
        return field_name.replace('_', ' ')

    # ── folder + step builders ─────────────────────────────────────────────
    def _open_folder(self, name: str):
        self.folder_stack.append(('folder', name))
        self.steps.append({'type': 'folder', 'name': name, 'depth': len(self.folder_stack) - 1})

    def _close_folder(self):
        if self.folder_stack:
            kind, name = self.folder_stack.pop()
            self.steps.append({'type': 'folder_end', 'name': name,
                                'depth': len(self.folder_stack)})

    def _open_block(self, name: str):
        self.folder_stack.append(('block', name))
        self.steps.append({'type': 'block_start', 'name': name,
                            'depth': len(self.folder_stack) - 1})

    def _close_block(self):
        if self.folder_stack:
            kind, name = self.folder_stack.pop()
            self.steps.append({'type': 'block_end', 'name': name,
                                'depth': len(self.folder_stack)})

    def _close_folders_to_depth(self, depth: int):
        while len(self.folder_stack) > depth:
            kind, name = self.folder_stack.pop()
            self.steps.append({'type': f'{kind}_end', 'name': name,
                                'depth': len(self.folder_stack)})

    def _emit_or_extend_step(self, step_name: str, module_name: str, action: dict):
        # If we already have a step open for this name+module pair, append.
        if (self.pending_step_actions
                and self.pending_step_actions[0] == (step_name, module_name)):
            self.pending_step_actions[1].append(action)
            return
        # Different step → flush previous, start new
        self._flush_step()
        self.pending_step_actions = (step_name, module_name), [action]

    def _flush_step(self):
        if not self.pending_step_actions: return
        if isinstance(self.pending_step_actions, list) and not self.pending_step_actions:
            return
        (name, module), actions = self.pending_step_actions
        # Drop locator None for waiting-style
        clean_acts = []
        for a in actions:
            ca = {k: v for k, v in a.items() if v is not None}
            if 'locator' in ca and not ca['locator'].get('primary'):
                ca.pop('locator', None)
            clean_acts.append(ca)
        # Emit step even when actions is empty — the @tosca step marker is the
        # source of truth (skipped TBox modules have no actions but still need
        # the step entity for round-trip).
        self.steps.append({
            'type': 'step', 'name': name, 'module': module,
            'depth': len(self.folder_stack),
            'actions': clean_acts,
        })
        self.pending_step_actions = []


# ──────────────────────────────────────────────────────────────────────────────
# Entry point used by gen_tsu.py
# ──────────────────────────────────────────────────────────────────────────────
def build_manifest_from_spec(spec_path, pages_dir, base_manifest=None):
    spec_path  = Path(spec_path)
    pages_dir  = Path(pages_dir) if pages_dir else None
    catalog, rev_index = ([], {})
    if pages_dir and pages_dir.exists():
        catalog, rev_index = parse_pages_dir(pages_dir)
    builder = SpecToManifest(catalog, rev_index, base_manifest)
    return builder.build(spec_path)


if __name__ == '__main__':
    import sys, json
    if len(sys.argv) < 3:
        print('usage: spec_to_manifest.py <spec.ts> <pages_dir> [base_manifest.json]')
        sys.exit(1)
    base = None
    if len(sys.argv) >= 4:
        base = json.loads(Path(sys.argv[3]).read_text())
    out = build_manifest_from_spec(sys.argv[1], sys.argv[2], base)
    print(json.dumps(out, ensure_ascii=False, indent=2))
